"""initial migration

Revision ID: 221638676d7c
Revises: af4e980d1b4a
Create Date: 2024-01-13 12:33:47.523050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221638676d7c'
down_revision = 'af4e980d1b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
